# Generated by Django 3.1.6 on 2021-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='start_with_preview',
            field=models.BooleanField(default=True, verbose_name='Начало статьи-картинка?'),
        ),
    ]
