# Generated by Django 3.1.6 on 2021-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_start_with_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='preview',
            field=models.ImageField(upload_to='articles_preview', verbose_name='Картинка'),
        ),
    ]
