# Generated by Django 3.1.6 on 2021-02-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210219_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_News',
        ),
    ]
