# Generated by Django 3.1.6 on 2021-03-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210223_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='text',
        ),
    ]
