# Generated by Django 3.1.6 on 2021-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210316_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Загаловок')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
