# Generated by Django 3.1.6 on 2021-03-16 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210316_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newsstore',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category_news', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='newsstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsstore',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsstore',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsstore',
            name='text',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
