# Generated by Django 3.1.6 on 2021-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210304_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='level',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Frird')], default=1, verbose_name='Уровень сложности'),
            preserve_default=False,
        ),
    ]
