# Generated by Django 3.1.6 on 2021-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='level',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Fhird')], default=1, verbose_name='Уровень сложности'),
        ),
    ]
